# Generated by Django 6.0 on 2026-04-29 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vendedor', 'Vendedor'), ('secretaria', 'Secretaria'), ('cliente_comprador', 'Cliente Comprador')], max_length=20, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('preferred_language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('ru', 'Русский')], default='es', max_length=2, verbose_name='Idioma preferido')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Debe cambiar contraseña')),
                ('temp_password_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiración de contraseña temporal')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='Intentos fallidos')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='AsignacionSecretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignada el')),
                ('cliente', models.ForeignKey(limit_choices_to={'role': 'cliente_comprador'}, on_delete=django.db.models.deletion.CASCADE, related_name='secretarias_asignadas', to='cuentas.perfil', verbose_name='Cliente comprador')),
                ('secretaria', models.ForeignKey(limit_choices_to={'role': 'secretaria'}, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to='cuentas.perfil', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Asignación Secretaria-Cliente',
                'verbose_name_plural': 'Asignaciones Secretaria-Cliente',
                'unique_together': {('secretaria', 'cliente')},
            },
        ),
    ]
