# Generated by Django 6.0 on 2026-04-29 21:39

import django.db.models.deletion
import django.utils.timezone
import reclamos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('numero_cargamento', models.CharField(max_length=100, verbose_name='Número de cargamento')),
                ('fecha_reclamo', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del reclamo')),
                ('variedad_rosa', models.CharField(max_length=100, verbose_name='Variedad de rosa')),
                ('cantidad_afectada', models.PositiveIntegerField(verbose_name='Cantidad afectada')),
                ('tipo_problema', models.CharField(choices=[('botones_danados', 'Botones dañados'), ('rosas_marchitas', 'Rosas marchitas'), ('problema_frio', 'Problema de frío'), ('variedad_incorrecta', 'Variedad incorrecta'), ('cantidad_faltante', 'Cantidad faltante'), ('empaque_danado', 'Empaque dañado'), ('otro', 'Otro')], max_length=25, verbose_name='Tipo de problema')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='cuentas.perfil', verbose_name='Cliente')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_asignados', to='cuentas.perfil', verbose_name='Secretaria asignada')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=reclamos.models.evidencia_path, verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='reclamos.reclamo', verbose_name='Reclamo')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cuentas.perfil', verbose_name='Autor')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='reclamos.reclamo', verbose_name='Reclamo')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['created_at'],
            },
        ),
    ]
