# Generated by Django 6.0 on 2026-05-14 04:21

import django.db.models.deletion
import reclamos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categoría')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de Problema',
                'verbose_name_plural': 'Categorías de Problemas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MotivoRechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, verbose_name='Motivo de rechazo')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivo de Rechazo',
            },
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=25, unique=True, verbose_name='Número')),
                ('variedad_rosa', models.CharField(max_length=100, verbose_name='Variedad de rosa')),
                ('numero_guia_master', models.CharField(max_length=100, verbose_name='Número de Guía Master')),
                ('fecha_despacho', models.DateField(verbose_name='Fecha de despacho')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('estado', models.CharField(choices=[('pendiente_validacion', 'Pendiente Validación'), ('en_validacion', 'En Validación'), ('aprobado_pendiente', 'Aprobado - Pendiente Asignación'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('en_investigacion', 'En Investigación'), ('resolucion_propuesta', 'Resolución Propuesta'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente_validacion', max_length=25, verbose_name='Estado')),
                ('observaciones_internas_calidad', models.TextField(blank=True, verbose_name='Observaciones Internas (Calidad)')),
                ('zona_horaria_cliente', models.CharField(default='America/New_York', max_length=50, verbose_name='Zona horaria cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='cuentas.perfil', verbose_name='Cliente')),
                ('inspector_calidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_inspeccionados', to='cuentas.perfil', verbose_name='Inspector de Calidad')),
                ('motivo_rechazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclamos.motivorechazo', verbose_name='Motivo de Rechazo')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'ordering': ['-created_at'],
                'permissions': [('puede_validar_calidad', 'Puede validar reclamos como Control de Calidad'), ('puede_ver_gerencia', 'Puede ver dashboard gerencial')],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=25)),
                ('estado_nuevo', models.CharField(max_length=25)),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios del cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.perfil')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reclamos.reclamo')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=reclamos.models.evidencia_path, verbose_name='Archivo')),
                ('descripcion_adjunto', models.CharField(blank=True, max_length=200, verbose_name='¿Qué muestra esta evidencia?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='reclamos.reclamo')),
            ],
            options={
                'verbose_name': 'Evidencia',
            },
        ),
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(verbose_name='Puntuación (1 a 5)')),
                ('comentarios_finales', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reclamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reclamos.reclamo')),
            ],
            options={
                'verbose_name': 'Encuesta de Satisfacción',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('es_interno', models.BooleanField(default=False, verbose_name='Nota interna (No visible para cliente)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cuentas.perfil')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='reclamos.reclamo')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Tipo de Problema')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='reclamos.categoriaproblema')),
            ],
            options={
                'verbose_name': 'Tipo de Problema',
                'verbose_name_plural': 'Tipos de Problemas',
            },
        ),
        migrations.AddField(
            model_name='reclamo',
            name='tipo_problema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reclamos.tipoproblema', verbose_name='Tipo de problema'),
        ),
        migrations.CreateModel(
            name='AsignacionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento (ej. Poscosecha)')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('accion_tomada', models.TextField(blank=True, verbose_name='Acciones tomadas')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_reclamos', to='cuentas.perfil')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_asignadas', to='reclamos.reclamo')),
            ],
            options={
                'verbose_name': 'Asignación a Área',
                'unique_together': {('reclamo', 'responsable')},
            },
        ),
    ]
